# Generated by Django 5.2.17 on 2026-09-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_user_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
