# Generated by Django 5.2.17 on 2026-09-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkinglocation_latitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglocation',
            name='latitude',
        ),
    ]
