# Generated by Django 5.2.17 on 2026-10-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_remove_parkinglocation_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
